//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orm_Basefirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avion()
        {
            this.Incidents = new HashSet<Incident>();
            this.Voyages = new HashSet<Voyage>();
        }
    
        public long Id { get; set; }
        public string Modele { get; set; }
        public bool Disponible { get; set; }
        public Nullable<int> NbPlaceBusiness { get; set; }
        public Nullable<int> NbPlacePremiere { get; set; }
        public Nullable<int> NbPlacePremium { get; set; }
        public string NbPlaceEconomique { get; set; }
        public Nullable<int> NbPlaceEquipege { get; set; }
        public bool Proprietaire { get; set; }
        public string CodeAeroport { get; set; }
    
        public virtual Aeroport Aeroport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incident> Incidents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voyage> Voyages { get; set; }
    }
}
