//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orm_Basefirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baggage
    {
        public long Id { get; set; }
        public double Poids_Kg_ { get; set; }
        public decimal Tarifs { get; set; }
        public long IdClient { get; set; }
        public long IdVoyages { get; set; }
        public long IdBillet { get; set; }
    
        public virtual Billet Billet { get; set; }
        public virtual Client Client { get; set; }
        public virtual Voyage Voyage { get; set; }
    }
}
