//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Billet()
        {
            this.Baggages = new HashSet<Baggage>();
        }
    
        public long Id { get; set; }
        public int IdTarifs { get; set; }
        public long IdVoyages { get; set; }
        public long IdClient { get; set; }
        public int PrixPendantAchat { get; set; }
        public bool Reduction { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Baggage> Baggages { get; set; }
        public virtual Client Client { get; set; }
        public virtual Tarif Tarif { get; set; }
        public virtual Voyage Voyage { get; set; }
    }
}
