//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjetBDD2Entities : DbContext
    {
        public ProjetBDD2Entities()
            : base("name=ProjetBDD2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aeroport> Aeroports { get; set; }
        public virtual DbSet<Avion> Avions { get; set; }
        public virtual DbSet<Baggage> Baggages { get; set; }
        public virtual DbSet<Billet> Billets { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Embarquement> Embarquements { get; set; }
        public virtual DbSet<Employe> Employes { get; set; }
        public virtual DbSet<Incident> Incidents { get; set; }
        public virtual DbSet<Maintenance> Maintenances { get; set; }
        public virtual DbSet<Naviguant> Naviguants { get; set; }
        public virtual DbSet<Sol> Sols { get; set; }
        public virtual DbSet<Tarif> Tarifs { get; set; }
        public virtual DbSet<Vol> Vols { get; set; }
        public virtual DbSet<Voyage> Voyages { get; set; }
    }
}
