//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orm_basefirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public int Id { get; set; }
        public int IndiceGravite { get; set; }
        public string Commentaire { get; set; }
        public System.DateTime Date { get; set; }
        public long idEmploye { get; set; }
        public long idAvion { get; set; }
        public int IdMaintenance { get; set; }
    
        public virtual Avion Avion { get; set; }
        public virtual Employe Employe { get; set; }
        public virtual Maintenance Maintenance { get; set; }
    }
}
